on:
  push:
    branches:
    - master

name: TruffleHog Secret Scanner

jobs:
  filter-to-pr-open-synced:
    runs-on: ubuntu-latest
    steps:
    - name: 1-filter-checkout-master
      uses: actions/checkout@master
    - name: 2-filter-to-pr-open-synced
      uses: actions/bin/filter@master
    - name: trufflehog-secret-scanner
      uses: broadinstitute/broad-security-actions-github/truffleHog@master
      env:
        TH_ACTION_WORKING_DIR: .