on:
  push:
    branches:
    - master

name: TruffleHog Secret Scanner

jobs:
  filter-to-pr-open-synced:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: broadinstitute/broad-security-actions-github/truffleHog@master
      env:
        TH_MAX_DEPTH: 1
